import { DEFAULT_LANGUAGE } from "./config.ts";

/**
 * IANA timezone → language name (config.ts의 EMAIL_CONTENT 키와 일치)
 * Supabase CSV 기준 287개 timezone 전체 매핑
 * 매핑에 없는 timezone은 English 폴백
 */
const TIMEZONE_TO_LANGUAGE: Record<string, string> = {
  // ===================== Africa =====================
  "Africa/Abidjan": "French",
  "Africa/Accra": "English",
  "Africa/Addis_Ababa": "Amharic",
  "Africa/Algiers": "Arabic",
  "Africa/Bamako": "French",
  "Africa/Banjul": "English",
  "Africa/Blantyre": "English",
  "Africa/Brazzaville": "French",
  "Africa/Bujumbura": "French",
  "Africa/Cairo": "Arabic",
  "Africa/Casablanca": "Arabic",
  "Africa/Ceuta": "Spanish",
  "Africa/Conakry": "French",
  "Africa/Dakar": "French",
  "Africa/Dar_es_Salaam": "Swahili",
  "Africa/Djibouti": "French",
  "Africa/Douala": "French",
  "Africa/El_Aaiun": "Arabic",
  "Africa/Freetown": "English",
  "Africa/Gaborone": "English",
  "Africa/Harare": "English",
  "Africa/Johannesburg": "English",
  "Africa/Kampala": "English",
  "Africa/Khartoum": "Arabic",
  "Africa/Kigali": "French",
  "Africa/Kinshasa": "French",
  "Africa/Lagos": "English",
  "Africa/Libreville": "French",
  "Africa/Lome": "French",
  "Africa/Luanda": "Portuguese",
  "Africa/Lubumbashi": "French",
  "Africa/Lusaka": "English",
  "Africa/Maputo": "Portuguese",
  "Africa/Maseru": "English",
  "Africa/Mbabane": "English",
  "Africa/Mogadishu": "Somali",
  "Africa/Monrovia": "English",
  "Africa/Nairobi": "Swahili",
  "Africa/Ndjamena": "French",
  "Africa/Nouakchott": "Arabic",
  "Africa/Ouagadougou": "French",
  "Africa/Porto-Novo": "French",
  "Africa/Tripoli": "Arabic",
  "Africa/Tunis": "Arabic",
  "Africa/Windhoek": "English",

  // ===================== America =====================
  // 북미 (영어)
  "America/Anchorage": "English",
  "America/Boise": "English",
  "America/Chicago": "English",
  "America/Denver": "English",
  "America/Detroit": "English",
  "America/Edmonton": "English",
  "America/Halifax": "English",
  "America/Indiana/Indianapolis": "English",
  "America/Juneau": "English",
  "America/Los_Angeles": "English",
  "America/Menominee": "English",
  "America/New_York": "English",
  "America/Phoenix": "English",
  "America/Regina": "English",
  "America/St_Johns": "English",
  "America/Toronto": "English",
  "America/Vancouver": "English",
  "America/Winnipeg": "English",

  // 캐나다 불어권
  "America/Montreal": "French",

  // 브라질 (포르투갈어)
  "America/Bahia": "Portuguese",
  "America/Belem": "Portuguese",
  "America/Boa_Vista": "Portuguese",
  "America/Campo_Grande": "Portuguese",
  "America/Cuiaba": "Portuguese",
  "America/Fortaleza": "Portuguese",
  "America/Manaus": "Portuguese",
  "America/Recife": "Portuguese",
  "America/Rio_Branco": "Portuguese",
  "America/Sao_Paulo": "Portuguese",

  // 중남미 (스페인어)
  "America/Argentina/Buenos_Aires": "Spanish",
  "America/Argentina/Cordoba": "Spanish",
  "America/Argentina/Tucuman": "Spanish",
  "America/Asuncion": "Spanish",
  "America/Bogota": "Spanish",
  "America/Buenos_Aires": "Spanish",
  "America/Cancun": "Spanish",
  "America/Caracas": "Spanish",
  "America/Chihuahua": "Spanish",
  "America/Ciudad_Juarez": "Spanish",
  "America/Cordoba": "Spanish",
  "America/Costa_Rica": "Spanish",
  "America/El_Salvador": "Spanish",
  "America/Guatemala": "Spanish",
  "America/Guayaquil": "Spanish",
  "America/Havana": "Spanish",
  "America/Hermosillo": "Spanish",
  "America/La_Paz": "Spanish",
  "America/Lima": "Spanish",
  "America/Managua": "Spanish",
  "America/Matamoros": "Spanish",
  "America/Mazatlan": "Spanish",
  "America/Mendoza": "Spanish",
  "America/Merida": "Spanish",
  "America/Mexico_City": "Spanish",
  "America/Monterrey": "Spanish",
  "America/Montevideo": "Spanish",
  "America/Panama": "Spanish",
  "America/Punta_Arenas": "Spanish",
  "America/Santiago": "Spanish",
  "America/Santo_Domingo": "Spanish",
  "America/Tegucigalpa": "Spanish",
  "America/Tijuana": "Spanish",

  // 카리브/기타 (영어)
  "America/Aruba": "English",
  "America/Barbados": "English",
  "America/Belize": "English",
  "America/Grand_Turk": "English",
  "America/Guadeloupe": "French",
  "America/Jamaica": "English",
  "America/Martinique": "French",
  "America/Nassau": "English",
  "America/Port_of_Spain": "English",
  "America/Puerto_Rico": "Spanish",
  "America/St_Barthelemy": "French",
  "America/Tortola": "English",

  // 기타 아메리카
  "America/Cayenne": "French",
  "America/Curacao": "English",
  "America/Godthab": "English",
  "America/Guyana": "English",
  "America/Nuuk": "English",
  "America/Paramaribo": "English",
  "America/Port-au-Prince": "French",

  // ===================== Asia =====================
  // 동아시아
  "Asia/Seoul": "Korean",
  "Asia/Tokyo": "Japanese",
  "Asia/Shanghai": "Chinese",
  "Asia/Hong_Kong": "Chinese",
  "Asia/Taipei": "Chinese",
  "Asia/Macau": "Chinese",
  "Asia/Ulaanbaatar": "Mongolian",
  "Asia/Choibalsan": "Mongolian",
  "Asia/Hovd": "Mongolian",

  // 동남아시아
  "Asia/Bangkok": "Thai",
  "Asia/Ho_Chi_Minh": "Vietnamese",
  "Asia/Saigon": "Vietnamese",
  "Asia/Jakarta": "Indonesian",
  "Asia/Jayapura": "Indonesian",
  "Asia/Makassar": "Indonesian",
  "Asia/Pontianak": "Indonesian",
  "Asia/Manila": "Filipino",
  "Asia/Kuala_Lumpur": "Malay",
  "Asia/Kuching": "Malay",
  "Asia/Phnom_Penh": "Khmer",
  "Asia/Vientiane": "Lao",
  "Asia/Yangon": "Burmese",
  "Asia/Rangoon": "Burmese",
  "Asia/Singapore": "English",
  "Asia/Brunei": "Malay",
  "Asia/Dili": "Portuguese",

  // 남아시아
  "Asia/Kolkata": "Hindi",
  "Asia/Calcutta": "Hindi",
  "Asia/Dhaka": "Bengali",
  "Asia/Kathmandu": "Nepali",
  "Asia/Katmandu": "Nepali",
  "Asia/Colombo": "Sinhala",
  "Asia/Karachi": "Urdu",
  "Asia/Thimphu": "Dzongkha",

  // 중앙아시아
  "Asia/Almaty": "Kazakh",
  "Asia/Aqtau": "Kazakh",
  "Asia/Atyrau": "Kazakh",
  "Asia/Oral": "Kazakh",
  "Asia/Qyzylorda": "Kazakh",
  "Asia/Tashkent": "Uzbek",
  "Asia/Samarkand": "Uzbek",
  "Asia/Bishkek": "Kyrgyz",
  "Asia/Dushanbe": "Tajik",
  "Asia/Ashgabat": "Turkmen",

  // 서아시아 / 중동
  "Asia/Tehran": "Persian",
  "Asia/Kabul": "Dari",
  "Asia/Jerusalem": "Hebrew",
  "Asia/Hebron": "Arabic",
  "Asia/Baku": "Azerbaijani",
  "Asia/Tbilisi": "Georgian",
  "Asia/Yerevan": "Armenian",

  // 아랍권
  "Asia/Aden": "Arabic",
  "Asia/Amman": "Arabic",
  "Asia/Baghdad": "Arabic",
  "Asia/Bahrain": "Arabic",
  "Asia/Beirut": "Arabic",
  "Asia/Damascus": "Arabic",
  "Asia/Dubai": "Arabic",
  "Asia/Kuwait": "Arabic",
  "Asia/Muscat": "Arabic",
  "Asia/Qatar": "Arabic",
  "Asia/Riyadh": "Arabic",
  "Asia/Nicosia": "Greek",

  // 러시아 (아시아 지역)
  "Asia/Barnaul": "Russian",
  "Asia/Chita": "Russian",
  "Asia/Irkutsk": "Russian",
  "Asia/Kamchatka": "Russian",
  "Asia/Krasnoyarsk": "Russian",
  "Asia/Novosibirsk": "Russian",
  "Asia/Omsk": "Russian",
  "Asia/Sakhalin": "Russian",
  "Asia/Vladivostok": "Russian",
  "Asia/Yakutsk": "Russian",
  "Asia/Yekaterinburg": "Russian",

  // ===================== Atlantic =====================
  "Atlantic/Azores": "Portuguese",
  "Atlantic/Bermuda": "English",
  "Atlantic/Canary": "Spanish",
  "Atlantic/Cape_Verde": "Portuguese",
  "Atlantic/Faroe": "Faroese",
  "Atlantic/Madeira": "Portuguese",
  "Atlantic/Reykjavik": "Icelandic",

  // ===================== Australia =====================
  "Australia/Adelaide": "English",
  "Australia/Brisbane": "English",
  "Australia/Darwin": "English",
  "Australia/Hobart": "English",
  "Australia/Melbourne": "English",
  "Australia/Perth": "English",
  "Australia/Sydney": "English",

  // ===================== Europe =====================
  "Europe/Amsterdam": "Dutch",
  "Europe/Andorra": "Catalan",
  "Europe/Athens": "Greek",
  "Europe/Belgrade": "Serbian",
  "Europe/Berlin": "German",
  "Europe/Bratislava": "Slovak",
  "Europe/Brussels": "English",
  "Europe/Bucharest": "Romanian",
  "Europe/Budapest": "Hungarian",
  "Europe/Chisinau": "Romanian",
  "Europe/Copenhagen": "Danish",
  "Europe/Dublin": "English",
  "Europe/Guernsey": "English",
  "Europe/Helsinki": "Finnish",
  "Europe/Istanbul": "Turkish",
  "Europe/Jersey": "English",
  "Europe/Kaliningrad": "Russian",
  "Europe/Kiev": "Ukrainian",
  "Europe/Kirov": "Russian",
  "Europe/Kyiv": "Ukrainian",
  "Europe/Lisbon": "Portuguese",
  "Europe/Ljubljana": "Slovenian",
  "Europe/London": "English",
  "Europe/Luxembourg": "French",
  "Europe/Madrid": "Spanish",
  "Europe/Malta": "Maltese",
  "Europe/Minsk": "Belarusian",
  "Europe/Monaco": "French",
  "Europe/Moscow": "Russian",
  "Europe/Oslo": "Norwegian",
  "Europe/Paris": "French",
  "Europe/Podgorica": "Serbian",
  "Europe/Prague": "Czech",
  "Europe/Riga": "Latvian",
  "Europe/Rome": "Italian",
  "Europe/Samara": "Russian",
  "Europe/Sarajevo": "Bosnian",
  "Europe/Saratov": "Russian",
  "Europe/Skopje": "Macedonian",
  "Europe/Sofia": "Bulgarian",
  "Europe/Stockholm": "Swedish",
  "Europe/Tallinn": "Estonian",
  "Europe/Tirane": "Albanian",
  "Europe/Uzhgorod": "Ukrainian",
  "Europe/Vienna": "German",
  "Europe/Vilnius": "Lithuanian",
  "Europe/Volgograd": "Russian",
  "Europe/Warsaw": "Polish",
  "Europe/Zagreb": "Croatian",
  "Europe/Zurich": "German",

  // ===================== Indian =====================
  "Indian/Antananarivo": "Malagasy",
  "Indian/Maldives": "Dhivehi",
  "Indian/Mauritius": "English",
  "Indian/Reunion": "French",

  // ===================== Pacific =====================
  "Pacific/Apia": "Samoan",
  "Pacific/Auckland": "English",
  "Pacific/Fiji": "Fijian",
  "Pacific/Guadalcanal": "English",
  "Pacific/Guam": "English",
  "Pacific/Honolulu": "English",
  "Pacific/Midway": "English",
  "Pacific/Noumea": "French",
  "Pacific/Pago_Pago": "English",
  "Pacific/Port_Moresby": "English",
  "Pacific/Tahiti": "French",
  "Pacific/Tarawa": "English",

  // ===================== 비표준 =====================
  "Eire": "English",
  "Etc/GMT": "English",
  "Etc/GMT-1": "English",
  "Etc/GMT-3": "English",
  "US/Central": "English",
  "US/Eastern": "English",
  "US/Pacific": "English",
  "UTC": "English",
};

/**
 * IANA timezone을 config.ts의 언어 이름으로 변환
 * - 정확한 매핑 있으면 해당 언어
 * - 없으면 English
 */
export function getLanguageFromTimezone(timezone: string | null): string {
  if (!timezone) {
    return DEFAULT_LANGUAGE;
  }
  return TIMEZONE_TO_LANGUAGE[timezone] || DEFAULT_LANGUAGE;
}
